print('请输入姓名：')
name = input()
print('请输入qq号：')
qq = input()
print('请输入电话号:')
phone = input()
print('请输入地址：')
compAddress = input()
print('=='*20)
print('姓名：%s'%name)
print('qq:%s'%qq)
print('手机号：%s'%phone)
print('地址：%s'%compAddress)
print('=='*20)